#
# Makefile for USB Class drivers
# (one step up from the misc category)
#

obj-$(CONFIG_USB_ACM)		+= cdc-acm.o
obj-$(CONFIG_USB_C8320_ACM)	+= mdm8320_acm.o
obj-$(CONFIG_USB_ACM_TEST)	+= acm_test.o
obj-$(CONFIG_USB_PRINTER)	+= usblp.o
obj-$(CONFIG_USB_WDM)		+= cdc-wdm.o
obj-$(CONFIG_USB_TMC)		+= usbtmc.o
